# Generated by Django 3.2.18 on 2023-02-17 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioGeral',
            fields=[
                ('relatorio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sede.relatorio')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('entradas_sede', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entradas_locais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entradas_missoes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saidas_sede', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saidas_locais', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pgto_obreiros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aluguel_obreiros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('construcoes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assis_social', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('sede.relatorio',),
        ),
    ]
