# Generated by Django 3.2.18 on 2023-02-17 03:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('igreja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.user')),
                ('cpf', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('funcao', multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Pastor'), ('T', 'Tesoureiro'), ('TS', 'Tesoureiro Sede')], max_length=20)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario', to='igreja.igreja')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tesoureiro',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoCadastro',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.user')),
                ('funcao', multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Pastor'), ('T', 'Tesoureiro'), ('TS', 'Tesoureiro Sede')], max_length=20)),
                ('cpf', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('situacao', models.CharField(max_length=20)),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('igreja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SolcitacaoCadastro', to='igreja.igreja')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TesoureiroSede',
            fields=[
                ('tesoureiro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.tesoureiro')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuario.tesoureiro',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
