# Generated by Django 3.2.18 on 2023-02-17 03:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financa',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=200)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.user')),
                ('nome', models.CharField(max_length=100)),
                ('data_nasc', models.DateField()),
                ('sexo', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido')], max_length=20)),
                ('cpf', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dizimo',
            fields=[
                ('financa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='igreja.financa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('membro', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dizimos', to='igreja.membro')),
            ],
            bases=('igreja.financa',),
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('financa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='igreja.financa')),
                ('valor_dizimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_culto', multiselectfield.db.fields.MultiSelectField(choices=[('E', 'EBD'), ('N', 'Normal'), ('C', 'Ceia')], max_length=20)),
                ('validacao_pastor', models.BooleanField(default=False)),
            ],
            bases=('igreja.financa',),
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('financa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='igreja.financa')),
                ('descricao', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('igreja.financa',),
        ),
        migrations.CreateModel(
            name='RelatorioMensal',
            fields=[
                ('relatorio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sede.relatorio')),
                ('pagamento_obreiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('missoes_sede', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fundo_convencional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dizimos', models.ManyToManyField(related_name='RelatorioGeral', to='igreja.Dizimo')),
                ('ofertas', models.ManyToManyField(related_name='RelatorioGeral', to='igreja.Oferta')),
                ('saidas', models.ManyToManyField(related_name='RelatorioGeral', to='igreja.Saida')),
            ],
            bases=('sede.relatorio',),
        ),
    ]
