name: Pylint

on:
  push:
    branches: [ test/actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        
    - name: Set up Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "Action Pylint"
        
    - name: Upgrade setuptools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
    
    - name: Install dependencies
      run: |
        python -m pip install pylint
    
    - name: Analyze the code with pylint
      run: |
        pylint $(git ls-files '*.py') > pylint_report.txt || true
    
    - name: Generate Markdown report organized by file
      run: |
        awk -F ":" '
          BEGIN { print "<details>" }
          /^(\*{13})/ {
            if (NR > 1) { print "</table></details>" }
            filename = gensub(/[\* ]+Module /, "", "g", $2)
            print "<summary><h2>" filename "</h2></summary><table><tr><th>Severidade</th><th>Código do erro</th><th>Erro</th><th>Tipo</th></tr>"
          }
          /^([^:]+):([0-9]+):([0-9]+): ([A-Z0-9]+): (.+)$/ {
            printf("<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n", $4, $5, $6, $7)
          }
          END { print "</table></details>" }
        ' pylint_report.txt > pylint_report_organized_by_file.md


    - name: Check for changes
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes detected"
          exit 0
        fi
    - name: Commit changes
      run: |
        git add . && git commit -m ":wrench: chore: Add pylint issues"
        git push
