name: Pylint

on:
  push:
    branches: [test/actions]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
        
      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "Action Pylint"
        
      - name: Upgrade setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
    
      - name: Install dependencies
        run: |
          python -m pip install pylint
    
      - name: Analyze the code with pylint
        run: |
          pylint $(git ls-files '*.py') > pylint_report.txt || true
    
      - name: Generate Markdown report
        run: |
          awk -F ":" '
            BEGIN {
              count = 0
              # Imprime o título do relatório
              print "# Pylint Report"
              # Imprime o número total de erros encontrados pelo pylint
              print "\n**Total**: %d\n", system("wc -l < pylint_report.txt")
              # Imprime o cabeçalho da tabela
              print "| Arquivo | Linha | Erro | Código do erro | Tipo |"
              print "| ------- | ----- | ---- | -------------- | ---- |"
            }
            # Este bloco de código é executado para cada erro encontrado pelo pylint
            # O padrão é: nome_do_arquivo:linha:coluna: código_do_erro: mensagem_do_erro
            # Por exemplo: app.py:10:5: W0611: Unused import os
            /(.+):([0-9]+):[0-9]+: ([^:]+): (.+)/ {
              
              # Extrai o nome do arquivo e remove o caminho do diretório
              arquivo = $1
              sub(/^.*\//, "", arquivo)
              
              # Extrai o número da linha onde ocorreu o erro
              linha = $2
              
              # Formata o caminho do arquivo para incluir um link clicável no relatório
              caminho = "[" arquivo "](" $1 "#L" $2 ")"
              
              # Extrai o código do erro (por exemplo, W0611)
              codigo_erro = $4
              
              # Extrai a mensagem de erro
              erro = $5
              
              match($0, /\(([^)]+)\)$/, tipo)
              tipo_erro = tipo[1]
              
              # Extrai o tipo de erro (por exemplo, warning)
              # tipo_erro = gensub("[^\\(]*\\(\\([a-z-]+\\)\\).*", "\\1", "g", $5)
              
              # Imprime uma linha da tabela com as informações do erro
              print "| " caminho " | " linha " | " erro " | " codigo_erro " | "tipo_erro " |"
            }
          ' pylint_report.txt > PYREPORT.md

      - name: Check for changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected"
            exit 0
          fi

      - name: Commit changes
        run: |
          git add . && git commit -m ":wrench: chore: Add pylint issues"
          git push
